// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_earn_1000_coins = "CgkI1dHY38cZEAIQGw"; // <GPGSID>
        public const string achievement_defeat_50_enemies = "CgkI1dHY38cZEAIQBA"; // <GPGSID>
        public const string achievement_buy_a_x2 = "CgkI1dHY38cZEAIQKg"; // <GPGSID>
        public const string achievement_reach_lvl_40 = "CgkI1dHY38cZEAIQEQ"; // <GPGSID>
        public const string achievement_defeat_200_enemies = "CgkI1dHY38cZEAIQBg"; // <GPGSID>
        public const string achievement_earn_5000_coins = "CgkI1dHY38cZEAIQHA"; // <GPGSID>
        public const string achievement_reach_lvl_5 = "CgkI1dHY38cZEAIQDQ"; // <GPGSID>
        public const string achievement_score_25_000_points = "CgkI1dHY38cZEAIQFA"; // <GPGSID>
        public const string achievement_watch_7_ads = "CgkI1dHY38cZEAIQJg"; // <GPGSID>
        public const string achievement_5_gems_combo = "CgkI1dHY38cZEAIQCg"; // <GPGSID>
        public const string achievement_earn_100_coins = "CgkI1dHY38cZEAIQGQ"; // <GPGSID>
        public const string achievement_score_10_000_points = "CgkI1dHY38cZEAIQEw"; // <GPGSID>
        public const string achievement_collect_1_gem = "CgkI1dHY38cZEAIQHg"; // <GPGSID>
        public const string achievement_reach_lvl_10 = "CgkI1dHY38cZEAIQDg"; // <GPGSID>
        public const string achievement_buy_a_revive = "CgkI1dHY38cZEAIQKw"; // <GPGSID>
        public const string achievement_watch_25_ads = "CgkI1dHY38cZEAIQKA"; // <GPGSID>
        public const string achievement_watch_a_token_ad = "CgkI1dHY38cZEAIQJQ"; // <GPGSID>
        public const string achievement_reach_lvl_50 = "CgkI1dHY38cZEAIQEg"; // <GPGSID>
        public const string achievement_earn_10_000_coins = "CgkI1dHY38cZEAIQHQ"; // <GPGSID>
        public const string achievement_watch_10_ads = "CgkI1dHY38cZEAIQJw"; // <GPGSID>
        public const string achievement_collect_5_gems = "CgkI1dHY38cZEAIQHw"; // <GPGSID>
        public const string achievement_earn_500_coins = "CgkI1dHY38cZEAIQGg"; // <GPGSID>
        public const string achievement_7_gems_combo = "CgkI1dHY38cZEAIQCw"; // <GPGSID>
        public const string achievement_share_your_score = "CgkI1dHY38cZEAIQGA"; // <GPGSID>
        public const string achievement_collect_20_gems = "CgkI1dHY38cZEAIQIQ"; // <GPGSID>
        public const string achievement_reach_lvl_20 = "CgkI1dHY38cZEAIQDw"; // <GPGSID>
        public const string achievement_defeat_100_enemies = "CgkI1dHY38cZEAIQBQ"; // <GPGSID>
        public const string achievement_defeat_1000_enemies = "CgkI1dHY38cZEAIQCA"; // <GPGSID>
        public const string achievement_score_75_000_points = "CgkI1dHY38cZEAIQFg"; // <GPGSID>
        public const string achievement_collect_50_gems = "CgkI1dHY38cZEAIQIg"; // <GPGSID>
        public const string achievement_9_gems_combo = "CgkI1dHY38cZEAIQDA"; // <GPGSID>
        public const string achievement_score_100_000_points = "CgkI1dHY38cZEAIQFw"; // <GPGSID>
        public const string achievement_score_50_000_points = "CgkI1dHY38cZEAIQFQ"; // <GPGSID>
        public const string achievement_watch_a_x2_ad = "CgkI1dHY38cZEAIQJA"; // <GPGSID>
        public const string achievement_defeat_5_enemies = "CgkI1dHY38cZEAIQAg"; // <GPGSID>
        public const string achievement_reach_lvl_30 = "CgkI1dHY38cZEAIQEA"; // <GPGSID>
        public const string achievement_defeat_25_enemies = "CgkI1dHY38cZEAIQAw"; // <GPGSID>
        public const string achievement_watch_50_ads = "CgkI1dHY38cZEAIQKQ"; // <GPGSID>
        public const string achievement_watch_a_revive_ad = "CgkI1dHY38cZEAIQIw"; // <GPGSID>
        public const string achievement_buy_all_swords = "CgkI1dHY38cZEAIQLA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI1dHY38cZEAIQAA"; // <GPGSID>
        public const string achievement_collect_10_gems = "CgkI1dHY38cZEAIQIA"; // <GPGSID>
        public const string achievement_3_gems_combo = "CgkI1dHY38cZEAIQCQ"; // <GPGSID>
        public const string achievement_defeat_500_enemies = "CgkI1dHY38cZEAIQBw"; // <GPGSID>

}

